# Generated by Django 6.0.5 on 2026-06-01 08:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('reply_help', 'Помощь с ответом'), ('translation', 'Перевод'), ('rewrite', 'Переписать'), ('tone_change', 'Изменить тон'), ('analyze', 'Анализ чата')], max_length=20)),
                ('user_prompt', models.TextField()),
                ('target_language', models.CharField(blank=True, max_length=10)),
                ('tone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Запрос',
                'verbose_name_plural': 'AI Запросы',
                'db_table': 'ai_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_text', models.TextField()),
                ('model_used', models.CharField(default='gemini-pro', max_length=50)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('generation_time_ms', models.PositiveIntegerField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('feedback', models.SmallIntegerField(blank=True, choices=[(1, '👍 Хорошо'), (-1, '👎 Плохо')], null=True)),
                ('feedback_comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Ответ',
                'verbose_name_plural': 'AI Ответы',
                'db_table': 'ai_responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('me', 'Я'), ('other', 'Собеседник')], max_length=10)),
                ('content', models.TextField()),
                ('original_language', models.CharField(blank=True, max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'db_table': 'chat_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('messenger', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('context_summary', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_after', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Сессия чата',
                'verbose_name_plural': 'Сессии чатов',
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
