# Generated by Django 6.0.5 on 2026-06-01 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airesponse',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='chats.airequest'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chatsession'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to='chats.chatsession'),
        ),
        migrations.AddIndex(
            model_name='airesponse',
            index=models.Index(fields=['is_favorite'], name='ai_response_is_favo_838dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'is_favorite'], name='chat_sessio_user_id_5fad69_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['delete_after'], name='chat_sessio_delete__b4f16e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'timestamp'], name='chat_messag_session_4a3fea_idx'),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['user', 'created_at'], name='ai_requests_user_id_4c417c_idx'),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['session'], name='ai_requests_session_afadcc_idx'),
        ),
    ]
