# Generated by Django 6.0.5 on 2026-06-01 08:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('native_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'db_table': 'supported_languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_tone', models.CharField(choices=[('formal', 'Формальный'), ('friendly', 'Дружеский'), ('neutral', 'Нейтральный'), ('assertive', 'Уверенный'), ('empathetic', 'Эмпатичный')], default='neutral', max_length=20)),
                ('default_response_language', models.CharField(default='ru', max_length=10)),
                ('default_input_language', models.CharField(default='auto', max_length=10)),
                ('preferred_messenger', models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('auto_detect_language', models.BooleanField(default=True)),
                ('save_history', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_type', models.CharField(choices=[('reply_help', 'Помощь с ответом'), ('translation', 'Перевод'), ('rewrite', 'Переписать'), ('analyze', 'Анализ контекста'), ('tone_change', 'Изменить тон')], max_length=20)),
                ('tone', models.CharField(blank=True, choices=[('formal', 'Формальный'), ('friendly', 'Дружеский'), ('neutral', 'Нейтральный'), ('assertive', 'Уверенный'), ('empathetic', 'Эмпатичный')], max_length=20)),
                ('language', models.CharField(default='ru', max_length=10)),
                ('system_prompt', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Промпт шаблон',
                'verbose_name_plural': 'Промпт шаблоны',
                'db_table': 'prompt_templates',
                'unique_together': {('template_type', 'tone', 'language', 'version')},
            },
        ),
    ]
